### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by southpolesteve** [jjg/jsfs#62]
Apologies for the screenshot :/ Initial tests run by Gao on the office network show a significant gap between upload rate when storing directly to Google Storage vs JSFS. These are not concurrent uploads. Working on another benchmark for that case.

Benchmark code can be run by downloading the 10x ingest repo and running `upload-test.js`

![img_0742](https://cloud.githubusercontent.com/assets/471400/8316933/05e503ee-19c8-11e5-8d73-dd9a4cd5bef3.JPG)

**Comment by southpolesteve** [comment]
Output format:
<Destination>: <total time> | <upload rate megabytes> | <upload rate megabits > 

GCS = "Google Cloud Storage"
JSFS = JSFS

**Comment by jjg** [comment]
Cool, now I have a target to hit (a good old fashioned face-off :)

**Comment by southpolesteve** [comment]
FYI My outbound pipe at home isn't as big, but I still see a substantial difference. Shouldn't need to run tests only on the office.

**Comment by jjg** [comment]
I can always commandeer one of the idle MDP's if I need to run a test over that pipe :)

**Comment by jjg** [comment]
After a lot of experimentation it looks like this is a network-related problem.  Not a specific network, but something to do with transfers that traverse the network, and particularly wide-area-networks.

I have some theories but the upshot of this is it's not an internal limitation of JSFS (at least not at this scale), so I'm going to have to dig deeper into the differences between local and WAN communications.

**Comment by jjg** [comment]
After a lot of testing and experimentation I have some positive results.

I wasn't able to use @southpolesteve benchmark to test upload performance between Murfie -> Google Cloud VM (throws a segfault, I'm guessing there's some compiled code in one of the dependencies that isn't architecture-compatible with the MDP hardware?), but I wrote my own to more tightly monitor the HTTP conversation (it had similar "before changes" numbers as @southpolesteve's).  Here are the results running against the currently deployed build of JSFS:

````
notarealuser@mdp200:~/jsfs/experimental# node blowchunks.js 
Fri Jun 26 2015 12:37:01 GMT-0500 (CDT) 1       Uploading file
Fri Jun 26 2015 12:37:06 GMT-0500 (CDT) 0       File POST status: 200
Fri Jun 26 2015 12:37:06 GMT-0500 (CDT) 1       Upload completed in 4.77 seconds (6.697628732997167 megabytes per second)
````

Similar tests run against co-lo hardware at Supranet pushed 10 megabytes per second (which based on other unrelated tests I've run against those machines is probably a throttle kicking in on their end).

Due to packet fragmentation there is an upper bound on how fast a single upload can go, at some point the overhead in handling the many small chunks starts to add up but based on the tests I've run that limit is well above the maximum speed we've been able to upload to Google Cloud storage, and it can be mitigated by performing simultaneous uploads.

I was really surprised at how directly packet fragmentation impacts Node's HTTP server, I would have thought that those fragments would have been buffered further down the stack enough that by the time the were accessible at the application layer they would be more uniformly sized, but that doesn't appear to be the case.

@southpolesteve when you get a chance please have your benchmark re-run from the office, I'd like to compare those results to mine and see if we're in the same ballpark.

**Comment by southpolesteve** [comment]
Test was rerun by Marc. Adding this for the record. First example was a previous test run by Gao before the changes. ![jsfs-tests](https://cloud.githubusercontent.com/assets/471400/8417528/40792e4c-1e7b-11e5-8bd6-3a848c84a588.jpg)

**Comment by jjg** [comment]
Initial experimental deduplicating front-end results (for reference purposes):

````
moot@mdp200:~/jsfs/experimental# node blowchunks.js 
Thu Jul 02 2015 12:45:45 GMT-0500 (CDT) 1       Uploading file
Thu Jul 02 2015 12:45:46 GMT-0500 (CDT) 0       File POST status: 200
Thu Jul 02 2015 12:45:46 GMT-0500 (CDT) 1       Upload completed in 0.761 seconds (41.981194555054515 megabytes per second)
moot@mdp200:~/jsfs/experimental# node blowchunks.js 
Thu Jul 02 2015 12:46:30 GMT-0500 (CDT) 1       Uploading file
Thu Jul 02 2015 12:46:31 GMT-0500 (CDT) 0       File POST status: 200
Thu Jul 02 2015 12:46:31 GMT-0500 (CDT) 1       Upload completed in 0.468 seconds (68.26429285554804 megabytes per second)
````

**Comment by jjg** [comment]
I think we've arrived at the bottom of this issue (MTU limits).  Front-end mode addresses this, closing for now but re-open of there are any objections.
